contact: null
contributors: null
creators: null
description: None
dosdp_tools_options: --obo-prefixes=true
edit_format: owl
export_formats:
- owl
- obo
- json
github_org: monarch-initiative
gzip_main: false
id: mgpo
import_group:
  directory: imports/
  disabled: false
  ids: null
  products:
  - description: null
    id: iao
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: go
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: ro
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: uberon
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: pato
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: chebi
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: pr
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  rebuild_if_source_changes: true
import_pattern_ontology: false
license: Unspecified
namespaces:
- http://purl.obolibrary.org/obo/MGPO_
obo_format_options: ''
pattern_group: null
pattern_pipelines_group:
  disabled: false
  ids: null
  products:
  - description: null
    dosdp_tools_options: --obo-prefixes=true
    id: manual
    rebuild_if_source_changes: true
    robot_settings: null
  rebuild_if_source_changes: true
primary_release: full
reasoner: ELK
release_artefacts:
- base
- full
repo: glyco-phenotype-ontology
report_fail_on: ERROR
robot_java_args: ''
robot_settings: null
robot_version: null
robotemplate_group: null
subset_group: null
title: Molecular Glyco-Phenotype Ontology
travis_emails: null
uribase: http://purl.obolibrary.org/obo
use_dosdps: true
